@echo off
REM Flutter SSL Pinning Bypass Script for Windows
REM Usage: flutter_ssl_pinning_bypass.bat <APK_PATH> <APKTOOL_PATH> <APP_PACKAGE_NAME>
REM Example: flutter_ssl_pinning_bypass.bat app.apk apktool.jar com.example.app

setlocal enabledelayedexpansion

REM Check for required arguments
if "%~3"=="" (
    echo [ERROR] Missing required arguments
    echo Usage: %~nx0 ^<APK_PATH^> ^<APKTOOL_PATH^> ^<APP_PACKAGE_NAME^>
    echo Example: %~nx0 app.apk apktool.jar com.example.app
    exit /b 1
)

REM Set variables
set APK_PATH=%~1
set APKTOOL_PATH=%~2
set APP_PACKAGE_NAME=%~3
set TEMP_DIR=temp_apk
set OUTPUT_DIR=output
set LIB_PATH=%TEMP_DIR%\lib\arm64-v8a\libflutter.so
set DISASM_FILE=libflutter_disasm.txt
set FRIDA_SCRIPT=script.js

echo [*] Flutter SSL Pinning Bypass Script
echo [*] APK Path: %APK_PATH%
echo [*] Package Name: %APP_PACKAGE_NAME%
echo.

REM Check if APK exists
if not exist "%APK_PATH%" (
    echo [ERROR] APK file not found: %APK_PATH%
    exit /b 1
)

REM Check if apktool exists
if not exist "%APKTOOL_PATH%" (
    echo [ERROR] Apktool not found: %APKTOOL_PATH%
    exit /b 1
)

REM Create output directory
if not exist "%OUTPUT_DIR%" mkdir "%OUTPUT_DIR%"

REM Step 1: Decompile APK using apktool
echo [*] Step 1: Decompiling APK...
if exist "%TEMP_DIR%" rmdir /s /q "%TEMP_DIR%"
java -jar "%APKTOOL_PATH%" d "%APK_PATH%" -o "%TEMP_DIR%" -f
if errorlevel 1 (
    echo [ERROR] Failed to decompile APK
    exit /b 1
)
echo [+] APK decompiled successfully

REM Step 2: Check if libflutter.so exists
echo [*] Step 2: Checking for libflutter.so...
if not exist "%LIB_PATH%" (
    echo [ERROR] libflutter.so not found. This might not be a Flutter app.
    echo [*] Checking for alternate paths...
    if exist "%TEMP_DIR%\lib\armeabi-v7a\libflutter.so" (
        set LIB_PATH=%TEMP_DIR%\lib\armeabi-v7a\libflutter.so
        echo [+] Found libflutter.so at armeabi-v7a
    ) else (
        echo [ERROR] No libflutter.so found in any architecture
        exit /b 1
    )
)
echo [+] Found libflutter.so

REM Step 3: Extract SSL strings using strings command (requires strings.exe from SysInternals)
echo [*] Step 3: Extracting SSL-related strings...
where strings >nul 2>&1
if errorlevel 1 (
    echo [WARNING] 'strings' command not found. Download from: https://learn.microsoft.com/en-us/sysinternals/downloads/strings
    echo [*] Continuing without string extraction...
    set SSL_CLIENT_ADDR=UNKNOWN
    set SSL_SERVER_ADDR=UNKNOWN
) else (
    for /f "delims=" %%i in ('strings "%LIB_PATH%" ^| findstr /C:"ssl_client"') do set SSL_CLIENT_ADDR=%%i
    for /f "delims=" %%i in ('strings "%LIB_PATH%" ^| findstr /C:"ssl_server"') do set SSL_SERVER_ADDR=%%i
    echo [+] SSL Client Address: !SSL_CLIENT_ADDR!
    echo [+] SSL Server Address: !SSL_SERVER_ADDR!
)

REM Step 4: Disassemble libflutter.so using objdump (requires objdump from MinGW or similar)
echo [*] Step 4: Disassembling libflutter.so...
where objdump >nul 2>&1
if errorlevel 1 (
    echo [WARNING] 'objdump' not found. Install from MinGW or MSYS2
    echo [*] Continuing without disassembly...
) else (
    objdump -d "%LIB_PATH%" > "%DISASM_FILE%"
    if errorlevel 1 (
        echo [WARNING] Failed to disassemble
    ) else (
        echo [+] Disassembly saved to %DISASM_FILE%
    )
)

REM Step 5: Create Frida script
echo [*] Step 5: Creating Frida bypass script...
(
echo /**
echo  * Flutter SSL Pinning Bypass Script
echo  * Generated by flutter_ssl_pinning_bypass.bat
echo  */
echo.
echo console.log^("Flutter SSL Pinning Bypass - Starting..."^);
echo.
echo // Pattern matching for ssl_verify_peer_cert function
echo var config = {
echo     "android": {
echo         "arm64": [
echo             "F? 0F 1C F8 F? 5? 01 A9 F? 5? 02 A9 F? ?? 03 A9 ?? ?? ?? ?? 68 1A 40 F9"
echo         ],
echo         "arm": [
echo             "2D E9 F0 4F A3 B0 81 46 50 20 10 70"
echo         ]
echo     }
echo };
echo.
echo function hook_ssl_verify_result^(address^) {
echo     Interceptor.replace^(address, new NativeCallback^(function ^(ssl, out_alert^) {
echo         console.log^("[+] SSL verification hooked - Returning success"^);
echo         return 1; // Return success
echo     }, 'int', ['pointer', 'pointer']^)^);
echo }
echo.
echo function find_and_hook^(^) {
echo     try {
echo         var libflutter = Process.findModuleByName^("libflutter.so"^);
echo         if ^(!libflutter^) {
echo             console.log^("[-] libflutter.so not found"^);
echo             return;
echo         }
echo         console.log^("[+] Found libflutter.so at: " + libflutter.base^);
echo.
echo         // Search for the pattern
echo         var patterns = config.android.arm64;
echo         patterns.forEach^(function^(pattern^) {
echo             var matches = Memory.scanSync^(libflutter.base, libflutter.size, pattern^);
echo             if ^(matches.length ^> 0^) {
echo                 console.log^("[+] Found ssl_verify_peer_cert at: " + matches[0].address^);
echo                 hook_ssl_verify_result^(matches[0].address^);
echo             }
echo         }^);
echo.
echo         console.log^("[+] SSL Pinning bypass applied"^);
echo     } catch ^(e^) {
echo         console.log^("[-] Error: " + e^);
echo     }
echo }
echo.
echo // Wait for library to load
echo setTimeout^(find_and_hook, 1000^);
echo console.log^("[*] Waiting for libflutter.so to load..."^);
) > "%FRIDA_SCRIPT%"
echo [+] Frida script created: %FRIDA_SCRIPT%

REM Step 6: Setup ADB and Frida
echo.
echo [*] Step 6: Setting up Frida on device...
where adb >nul 2>&1
if errorlevel 1 (
    echo [ERROR] ADB not found. Install Android SDK Platform Tools
    echo Download from: https://developer.android.com/studio/releases/platform-tools
    exit /b 1
)

REM Check device connection
adb devices | findstr "device$" >nul
if errorlevel 1 (
    echo [ERROR] No Android device connected
    echo [*] Please connect an Android device with USB debugging enabled
    exit /b 1
)
echo [+] Android device detected

REM Check if Frida is installed
where frida >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Frida not installed
    echo [*] Install with: pip install frida-tools
    exit /b 1
)
echo [+] Frida tools found

REM Check if frida-server is running on device
adb shell "ps | grep frida-server" >nul 2>&1
if errorlevel 1 (
    echo [WARNING] Frida-server not running on device
    echo [*] Please start frida-server manually on the device:
    echo     1. Download frida-server for your device architecture
    echo     2. Push to device: adb push frida-server /data/local/tmp/
    echo     3. Set permissions: adb shell "chmod 755 /data/local/tmp/frida-server"
    echo     4. Run: adb shell "/data/local/tmp/frida-server &"
    echo.
    echo [?] Do you want to continue anyway? ^(Y/N^)
    set /p continue=
    if /i not "!continue!"=="Y" exit /b 1
)

REM Step 7: Run Frida with the script
echo.
echo [*] Step 7: Launching Frida hook...
echo [*] Starting application: %APP_PACKAGE_NAME%
echo [*] Press Ctrl+C to stop
echo.

frida -U -f "%APP_PACKAGE_NAME%" -l "%FRIDA_SCRIPT%" --no-pause

echo.
echo [*] Script execution completed
echo.
echo [*] Output files:
echo     - Frida Script: %FRIDA_SCRIPT%
echo     - Decompiled APK: %TEMP_DIR%
if exist "%DISASM_FILE%" echo     - Disassembly: %DISASM_FILE%
echo.
echo [*] To clean up temporary files, run: rmdir /s /q %TEMP_DIR%

endlocal
